const languages = [
  { "code": "af", "name": "Afrikaans" },
  { "code": "am", "name": "Amharic" },
  { "code": "ar", "name": "Arabic" },
  { "code": "bg", "name": "Bulgarian" },
  { "code": "bn", "name": "Bengali" },
  { "code": "bs", "name": "Bosnian" },
  { "code": "ca", "name": "Catalan" },
  { "code": "cs", "name": "Czech" },
  { "code": "cy", "name": "Welsh" },
  { "code": "da", "name": "Danish" },
  { "code": "de", "name": "German" },
  { "code": "el", "name": "Greek" },
  { "code": "en", "name": "English" },
  { "code": "es", "name": "Spanish" },
  { "code": "et", "name": "Estonian" },
  { "code": "eu", "name": "Basque" },
  { "code": "fi", "name": "Finnish" },
  { "code": "fr", "name": "French" },
  { "code": "fr-CA", "name": "French (Canada)" },
  { "code": "gl", "name": "Galician" },
  { "code": "gu", "name": "Gujarati" },
  { "code": "ha", "name": "Hausa" },
  { "code": "hi", "name": "Hindi" },
  { "code": "hr", "name": "Croatian" },
  { "code": "hu", "name": "Hungarian" },
  { "code": "id", "name": "Indonesian" },
  { "code": "is", "name": "Icelandic" },
  { "code": "it", "name": "Italian" },
  { "code": "iw", "name": "Hebrew" },
  { "code": "ja", "name": "Japanese" },
  { "code": "jw", "name": "Javanese" },
  { "code": "km", "name": "Khmer" },
  { "code": "kn", "name": "Kannada" },
  { "code": "ko", "name": "Korean" },
  { "code": "la", "name": "Latin" },
  { "code": "lt", "name": "Lithuanian" },
  { "code": "lv", "name": "Latvian" },
  { "code": "ml", "name": "Malayalam" },
  { "code": "mr", "name": "Marathi" },
  { "code": "ms", "name": "Malay" },
  { "code": "my", "name": "Myanmar (Burmese)" },
  { "code": "ne", "name": "Nepali" },
  { "code": "nl", "name": "Dutch" },
  { "code": "no", "name": "Norwegian" },
  { "code": "pa", "name": "Punjabi (Gurmukhi)" },
  { "code": "pl", "name": "Polish" },
  { "code": "pt", "name": "Portuguese (Brazil)" },
  { "code": "pt-PT", "name": "Portuguese (Portugal)" },
  { "code": "ro", "name": "Romanian" },
  { "code": "ru", "name": "Russian" },
  { "code": "si", "name": "Sinhala" },
  { "code": "sk", "name": "Slovak" },
  { "code": "sq", "name": "Albanian" },
  { "code": "sr", "name": "Serbian" },
  { "code": "su", "name": "Sundanese" },
  { "code": "sv", "name": "Swedish" },
  { "code": "sw", "name": "Swahili" },
  { "code": "ta", "name": "Tamil" },
  { "code": "te", "name": "Telugu" },
  { "code": "th", "name": "Thai" },
  { "code": "tl", "name": "Filipino" },
  { "code": "tr", "name": "Turkish" },
  { "code": "uk", "name": "Ukrainian" },
  { "code": "ur", "name": "Urdu" },
  { "code": "vi", "name": "Vietnamese" },
  { "code": "yue", "name": "Cantonese" },
  { "code": "zh-CN", "name": "Chinese (Simplified)" },
  { "code": "zh-TW", "name": "Chinese (Mandarin/Taiwan)" },
  { "code": "zh", "name": "Chinese (Mandarin)" }
];
  
  export default languages;
  